export const QUOTES = [
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
  { text: "You don't have to be extreme, just consistent.", author: "Unknown" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Train insane or remain the same.", author: "Unknown" },
  { text: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "The difference between the impossible and the possible lies in determination.", author: "Tommy Lasorda" },
  { text: "Champions aren't made in gyms. Champions are made from something deep inside them.", author: "Muhammad Ali" },
  { text: "It never gets easier, you just get better.", author: "Unknown" },
  { text: "Hybrid training is not a compromise — it's a complete athlete.", author: "Unknown" },
  { text: "Run when you can, walk when you have to, crawl if you must. Just never give up.", author: "Dean Karnazes" },
  { text: "The iron never lies to you.", author: "Henry Rollins" },
  { text: "Sweat is just fat crying.", author: "Unknown" },
  { text: "A one-hour workout is 4% of your day. No excuses.", author: "Unknown" },
  { text: "Endure the pain of discipline or suffer the pain of regret.", author: "Unknown" },
  { text: "The last three or four reps is what makes the muscle grow.", author: "Arnold Schwarzenegger" },
  { text: "No matter how slow you go, you're still lapping everyone on the couch.", author: "Unknown" },
  { text: "Strength is the product of struggle.", author: "Unknown" },
  { text: "The goal is not to be better than others — it's to be better than yesterday.", author: "Unknown" },
  { text: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "The only way to define your limits is to go beyond them.", author: "Arthur Clarke" },
  { text: "A strong body makes the mind strong.", author: "Thomas Jefferson" },
  { text: "You are one workout away from a good mood.", author: "Unknown" },
  { text: "The clock is ticking. Are you becoming the person you want to be?", author: "Greg Plitt" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Wake up. Work out. Look hot. Kick ass.", author: "Unknown" },
  { text: "The best project you'll ever work on is you.", author: "Unknown" },
  { text: "When you feel like stopping, think about why you started.", author: "Unknown" },
  { text: "Fitness is not about being better than someone else — it's about being better than you used to be.", author: "Unknown" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Hustle for that muscle.", author: "Unknown" },
  { text: "You don't find willpower. You create it.", author: "Unknown" },
  { text: "Some days you eat salads and go to the gym. Some days you eat cupcakes and refuse to put on pants. It's called balance.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Obsessed is a word the lazy use to describe the dedicated.", author: "Unknown" },
  { text: "The pain you feel today is the strength you feel tomorrow.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "Eat clean, train mean, get lean.", author: "Unknown" },
  { text: "Every champion was once a contender who refused to give up.", author: "Rocky Balboa" },
  { text: "Show up. Work hard. Be consistent. Results will come.", author: "Unknown" },
  { text: "If you're tired of starting over, stop giving up.", author: "Unknown" },
  { text: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { text: "The harder you work, the luckier you get.", author: "Gary Player" },
  { text: "Once you see results, it becomes an addiction.", author: "Unknown" },
  { text: "The body is your temple. Keep it pure and clean for the soul to reside in.", author: "B.K.S. Iyengar" },
  { text: "Training gives us an outlet for suppressed energies created by stress and thus tones the spirit.", author: "Arnold Schwarzenegger" },
  { text: "It's a slow process, but quitting won't speed it up.", author: "Unknown" },
  { text: "You didn't come this far to only come this far.", author: "Unknown" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you greater than any obstacle.", author: "Christian D. Larson" },
  { text: "Success starts with self-discipline.", author: "Unknown" },
  { text: "Push yourself because no one else is going to do it for you.", author: "Unknown" },
  { text: "There's no secret formula. I lift heavy, work hard, and aim to be the best.", author: "Ronnie Coleman" },
  { text: "Train hard, turn up, run your best, and the rest will take care of itself.", author: "Usain Bolt" },
  { text: "Excellence is not a singular act but a habit. You are what you repeatedly do.", author: "Shaquille O'Neal" },
  { text: "Fuel right, train hard, recover well. Repeat.", author: "Unknown" },
  { text: "The road to athletic greatness is not marked by perfection, but by the ability to constantly overcome adversity.", author: "Unknown" },
  { text: "Your only limit is your mind.", author: "Unknown" },
]

export function getDailyQuote() {
  const start = new Date(new Date().getFullYear(), 0, 0)
  const now = new Date()
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000)
  return QUOTES[dayOfYear % QUOTES.length]
}
